xcodeproj 'AeroGear-TODO.xcodeproj'

platform :ios, '5.0'

pod 'AeroGear', '1.0.1'

pod 'PullToRefresh', '0.0.1'
pod 'SVProgressHUD', '0.8'
pod 'Color-Picker-for-iOS', '0.1.1' 
pod 'ARGenericTableViewController', '1.0.0'
