xcodeproj 'AeroGear-TODO.xcodeproj'

platform :ios, '5.0'

pod 'AeroGear', :podspec => 'https://raw.github.com/aerogear/aerogear-ios/master/AeroGear.podspec'
pod 'PullToRefresh', '0.0.1'
pod 'SVProgressHUD', '0.8'
pod 'Color-Picker-for-iOS', '0.1.1' 
pod 'Mantle', '0.2.1'
